- hosts: ubuntu_main
  # gather_facts: no
  vars:
    nginx_port: 80
    local_project_path: /home/dobro/Desktop/work/ansible_hexlet
    server_name: 'This is server {{ ansible_hostname | upper }}'
    datetime: '{{ ansible_date_time["date"] }}'

  tasks:

    - name: install packages
      become: yes
      apt:
        name: 
          - git
          - nginx
          - cowsay
        state: present
        update_cache: yes 
      tags: [git]

    - name: copy nginx config
      become: yes
      template:
        src: '{{ local_project_path }}/nginx/nginx.conf'
        dest: /etc/nginx/
      notify:
        - restart nginx
      tags: [nginx]
    
    - name: register cowsay
      shell: cowsay 'This is server {{ server_name }}!'
      register: cowsay_result

    - name: copy html file
      become: yes
      template:
        src: '{{ local_project_path }}/ui/index.html'
        dest: /usr/share/nginx/html/
      tags: [ui]

  handlers:
  - name: restart nginx
    service:
      name: nginx
      state: reloaded
    become: yes
  