- hosts: yandex

  tasks:

    - name: install nginx
      become: yes
      apt:
        name: nginx
        state: latest

    - name: copy nginx config
      become: yes
      copy:
        src: /home/dobro/Desktop/work/ansible_hexlet/nginx/nginx.conf
        dest: /etc/nginx/
      notify:
        - restart nginx

    - name: copy html file
      become: yes
      copy:
        src: /home/dobro/Desktop/work/ansible_hexlet/ui/index.html
        dest: /usr/share/nginx/html/

  handlers:
  - name: restart nginx
    ansible.builtin.service:
      name: nginx
      state: reloaded
    become: yes
  