- hosts: digital_ocean
  # gather_facts: no
  vars:
    local_project_path: /home/dobro/Desktop/work/ansible_hexlet
    user_names:
      - jaime
      - sansa
      - robert

  tasks:

    - name: install git on Ubuntu
      become: yes
      apt:
        name: git
        state: present
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'
      tags: [packages, git]

    - name: install git on Centos
      become: yes
      yum:
        name: git
        state: present
        update_cache: yes
      when: ansible_distribution == 'CentOS'
      tags: [packages, git]

    - name: add test users
      become: yes
      user:
        name: "{{ item }}"
        state: present
      loop: "{{ user_names }}"
      tags: [users]

    - name: add ssh keys for test users
      authorized_key:
        user: '{{ item }}'
        state: present
        key: "{{ lookup('file', '{{ local_project_path }}/pub_ssh_keys/{{ item }}.pub') }}"
      loop: '{{ user_names }}'
      tags: [users, ssh]

    - name: copy users git config files
      become: yes
      template:
        src: '{{ local_project_path }}/git_configs/.gitconfig'
        dest: '/home/{{ item }}/.gitconfig'
      loop: "{{ user_names }}"
      tags: [users, git]
