- hosts: digital_ocean
  # gather_facts: no
  vars:
    local_project_path: /home/dobro/Desktop/work/ansible_hexlet

  tasks:

    - name: install nginx
      become: yes
      apt:
        name: nginx
        state: latest

    - name: copy nginx config
      become: yes
      template:
        src: '{{ local_project_path }}/nginx/nginx.conf'
        dest: /etc/nginx/
      notify:
        - restart nginx

    - name: copy html file
      become: yes
      template:
        src: '{{ local_project_path }}/ui/index.html'
        dest: /usr/share/nginx/html/

  handlers:
  - name: restart nginx
    service:
      name: nginx
      state: reloaded
    become: yes
  