- hosts: digital_ocean
  # gather_facts: no
  vars:
    nginx_port: 8080
    local_project_path: /home/dobro/Desktop/work/ansible_hexlet
    user_names:
      - jaime
      - sansa
      - robert
    server_name: 'This is server {{ ansible_hostname | upper }}'
    datetime: '{{ ansible_date_time["date"] }}'

  tasks:

    - name: install packages on Ubuntu
      become: yes
      apt:
        state: present
        name: 
          - git
          - nginx
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'
      tags: [packages]

    - name: install packages on Centos
      become: yes
      yum:
        state: present
        name: 
          - git
          - nginx
        update_cache: yes
      when: ansible_distribution == 'CentOS'
      tags: [packages]

    - name: copy nginx config
      become: yes
      template:
        src: '{{ local_project_path }}/nginx/nginx.conf'
        dest: /etc/nginx/
      notify:
        - restart nginx
      tags: [nginx]

    - name: copy template files
      become: yes
      template:
        src: '{{ local_project_path }}/ui/index.html'
        dest: /usr/share/nginx/html/
      tags: [ui]

    - name: add test users
      become: yes
      user:
        name: "{{ item }}"
        state: present
      loop: "{{ user_names }}"
      tags: [users]

    - name: add ssh keys for test users
      authorized_key:
        user: '{{ item }}'
        state: present
        key: "{{ lookup('file', '{{ local_project_path }}/pub_ssh_keys/{{ item }}.pub') }}"
      loop: '{{ user_names }}'
      tags: [users, ssh]

    - name: copy users git config files
      become: yes
      template:
        src: '{{ local_project_path }}/git_configs/.gitconfig'
        dest: '/home/{{ item }}/.gitconfig'
      loop: '{{ user_names }}'
      tags: [users, git]


  handlers:
  - name: restart nginx
    service:
      name: nginx
      state: reloaded
    become: yes
