- hosts: ubuntu_main
  gather_facts: no

  tasks:

    - name: add test users
      become: yes
      user:
        name: "{{ item }}"
        state: present
      loop: "{{ user_names }}"
      tags: [users]

    - name: add ssh keys for test users
      authorized_key:
        user: '{{ item }}'
        state: present
        key: "{{ lookup('file', '{{ local_project_path }}/pub_ssh_keys/{{ item }}.pub') }}"
      loop: '{{ user_names }}'
      tags: [users, ssh]

    - name: copy users git config files
      become: yes
      template:
        src: '{{ local_project_path }}/git_configs/.gitconfig'
        dest: '/home/{{ item }}/.gitconfig'
      loop: '{{ user_names }}'
      tags: [users, git]
